---
driver:
  name: ec2
  instance_type: t2.micro
  retryable_tries: 121
  aws_ssh-key_id: rjoshichefio
  shared_credentials_profile: "success-engineering"
  shared_credentials_file: "/home/centos/.aws/credentials"
  shared_config_file: "/home/centos/.aws/config"
  aws_region: "us-west-2"
  aws_ssh_key_pair_name: "rjoshi@chef.io"
  availability_zone: b
  instance_type: t2.micro
  #remaining attributes are in local yml file

provisioner:
  name: chef_zero
  cookbook_path: /hab/svc/jenkins/data/workspace/
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos7
    #driver_config:
    #  image_id: ami-4a80ac20
    driver:
      image_search:
        owner-id: "679593333241"
        name: "CentOS Linux 7 x86_64 HVM EBS ENA 1901_01-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-05713873c6794f575.4"
    transport:
      username: centos
      ssh_key: ~/.ssh/rjoshichefio.pem

suites:
  - name: default
    run_list:
      - recipe[learn_chef_httpd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

