---
driver:
  name: ec2
  instance_type: t2.micro
  retryable_tries: 121
  aws_profile = "success-engineering"
  aws_region = "us-west-2"
  aws_ssh_key_file = "/home/centos/.ssh/rjoshichefio.pem"
  aws_ssh_key_pair_name = "rjoshi@chef.io"
  #remaining attributes are in local yml file

provisioner:
  name: chef_zero
  cookbook_path: /hab/svc/jenkins/data/workspace/
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.4
    driver_config:
      image_id: ami-a042f4d8

suites:
  - name: default
    run_list:
      - recipe[learn_chef_httpd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
